sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Pv2ZwwL9vfpT0Gm9hMZczRFVjmsmOLhPcvZdW2WheifX7kj3FWoPkyIS6fkEW4uqntSmv2OeQhgf+G7j5YJrid6zAa65JP9W5nv+gtexP3A5kyGPD55YS0VrcsHu8O3UPjM7QEmxeYkbP/ewbKgEb/lT/OrfDoevSW7hkGqqdsI+IReJymudJooeQFBePqFU61yHf0pS0pYdG+5zcGL9JUAM0uwcbsDP5EQ4nqDcc9uzf4bp8nHrp+wX3S3V4Nhvl3Boq1gKQB3s1N2ZC/yIKzu7jWgKNiHKJYiYwSIXSHvAlYyhXU2OzEa4fCF/gyUOAOyrXzyj6MTCaC9SL6fQ/3JEd03OTDSkwDEvyZh6f4Ztbyz14uD7fSWnDNh2ilpqnyRnOOLyqcwbSQkmFMGu8OnqWJiDrHi/+O+ty1vlt/+cjwSo9xvLN9g86ORmA6maZrobxQ0B02ybRuTRKPTDPE/miGIbAbFqIKTa29mxMtgiD8Ti5bFk1peGK2jPyEjvi0vkunDdf61puTCUVuC7mBA5lgnfxR9TLkdcj2WLll4TvcFDN5/qz0wngnqJ5UT0j6Ih38DmgnT/HFVjIHrIh61ZxWvHWpMwB8RqOIRJyXAhaFUmdEWdjGiZeO1A+G6ZOwcBs9RTU08vb2p0CfGuw7v07FFRCznLsTdwsyprquY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Lady-of-the-Shroud_3095
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy